Image
chanchal-panpaliya/component-libraray pull request #7
Opened 2022-02-10 20:42 UTC by chanchal-panpaliya

please review my code . time is less and work is more . so , if its mandatory to change some code then please comment . last date submission is 16th .

project live - https://solutionground.netlify.app/

2022-02-11 06:35 UTC, Mohasin-Haque reviewed
You need to run prettier or format the code first. Then remove the commented part and also do care of using relative units. In every file. And remove the empty files

2022-02-11 06:35 UTC, Mohasin-Haque commented on image/Image/Image.css
> +.image-size-larger{
Please try to use relative units everywhere..If you have time .. else you can do it after 16

2022-02-16 04:06 UTC, prathmeshjagtap requested changes
Code seems good you have used constant naming convention throughout your code so it becomes easy to understand.

2022-02-16 04:06 UTC, prathmeshjagtap commented on image/Image/Image.css
> +    max-width: 25rem;
why the image was restricted to max-width: 25 rem,
Also, you can add object-fit: contain/cover to make it more precise.

2022-02-16 05:02 UTC, prathmeshjagtap approved these changes

2022-02-16 06:15 UTC, SanjayJatti approved these changes

2022-02-16 06:16 UTC, SanjayJatti commented
Code is clean. You can go ahead.

2022-02-16 12:55 UTC, merged